spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_watchlist
    username: tarakaram
    password: Apple@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # Don't let Hibernate auto-create tables, we want to use our SQL script
    show-sql: true     # (Optional) log queries for debugging
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always          # Always run SQL scripts at startup
      schema-locations: classpath:scripts/schema.sql  # reads only schema.sql and data.sql at specified location
